---
abstract: 'Template-Toolkit virtual methods and filters for Xslate (deprecated)'
author:
  - 'Fuji, Goro (gfx) <gfuji@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.0.56, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Xslate-Bridge-TT2
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Text::Xslate::Bridge::TT2:
    file: lib/Text/Xslate/Bridge/TT2.pm
    version: 1.0003
requires:
  Template: 2
  Text::Xslate: 0.1045
  parent: 0.2
  perl: 5.008001
resources:
  bugtracker: https://github.com/xslate/p5-Text-Xslate-Bridge-TT2/issues
  homepage: https://github.com/xslate/p5-Text-Xslate-Bridge-TT2
  repository: git://github.com/xslate/p5-Text-Xslate-Bridge-TT2.git
version: 1.0003
x_contributors:
  - 'Fuji, Goro <g.psy.va@gmail.com>'
